#!/usr/bin/env python3
"""Emit the two Phase 1 deliverables as markdown: the compose-failure catalogue
and the rewrite ledger.

    python3 make_ledger.py > ../results/REWRITE_LEDGER.md
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SWEEP = os.path.abspath(os.path.join(HERE, ".."))


def load(n):
    p = os.path.join(SWEEP, "results", n)
    return json.load(open(p)) if os.path.exists(p) else []


def clean(s, n=150):
    return " ".join(str(s or "").split())[:n]


def main():
    base = {r["id"]: r for r in load("phase1_compose.json")}
    variants = load("phase1r_variants.json")
    ledger = load("rewrite_ledger.json")
    gran = load("granularity.json")
    cm = json.load(open(os.path.join(SWEEP, "cost_model.json")))
    prov = cm.get("cell_provenance", {})

    print("# Compose-failure catalogue and rewrite ledger\n")
    print("Generated by `scripts/make_ledger.py` from the committed records, so "
          "it cannot drift from them. Every string in the `log says` column is "
          "what `qnn-context-binary-generator` printed on the board.\n")

    print("## 1. Compose-failure catalogue (whole-network baseline)\n")
    print("16 networks x 5 (backend, precision) pairs = 80 composes; **65 "
          "succeeded**. Every failure is HTA.\n")
    print("| network | IR ops | op set in the tile | backend | log says |")
    print("|---|---|---|---|---|")
    for nid, r in base.items():
        for be, v in sorted((r.get("compose") or {}).items()):
            if v.get("status") == "ok":
                continue
            kinds = ", ".join(sorted(r.get("ir_op_kinds") or {})[:9])
            print(f"| `{nid}` | {r['ir_ops']} | {kinds} | {be} | "
                  f"`{clean(v.get('reason') or v.get('status'))}` |")

    print("\n## 2. Rewrite ledger\n")
    print("A rewrite is a **candidate**. It is adopted for a lane only where it "
          "measured better than the base on that lane, and a numerics-changing "
          "rewrite is never adopted at all.\n")
    print("| base | chain | numerics | ir ops before -> after | composes on |")
    print("|---|---|---|---|---|")
    for v in variants:
        ok = sorted(k for k, c in (v.get("compose") or {}).items()
                    if c.get("status") == "ok")
        b = base[v["base"]]
        print(f"| `{v['base']}` | `{', '.join(v['rewrite_chain'])}` | "
              f"**{v['numerics']}** | {b['ir_ops']} -> {v['ir_ops']} | "
              f"{', '.join(ok)} |")

    print("\n### Per (network, lane): blocker, rewrite, and the measurement "
          "that justified adoption or rejection\n")
    print("All times are the median over five gap-phase passes, in ms.\n")
    print("| network | lane | blocker on the base | base | rewritten | "
          "numerics-changing probe | adopted | precision |")
    print("|---|---|---|---|---|---|---|---|")

    def ms(v):
        return f"{v/1000:.3f}" if v else "—"

    for r in ledger:
        print(f"| `{r['network']}` | {r['lane']} | "
              f"{('`' + clean(r['blocker'], 60) + '`') if r['blocker'] else '—'} | "
              f"{ms(r['base_us'])} | {ms(r['variant_us'])} | "
              f"{ms(r['numerics_changing_us'])} | {r['adopted'] or '—'} | "
              f"{r['adopted_precision'] or '—'} |")

    print("\n### Rewrites that were tried and did not win\n")
    lost = [r for r in ledger if r["variant_us"] and r["base_us"]
            and r["variant_us"] > r["base_us"]]
    if lost:
        print("| network | lane | base | rewritten | rewritten is worse by |")
        print("|---|---|---|---|---|")
        for r in lost:
            print(f"| `{r['network']}` | {r['lane']} | {ms(r['base_us'])} | "
                  f"{ms(r['variant_us'])} | "
                  f"{(r['variant_us']/r['base_us'] - 1)*100:.0f}% |")
        print("\nThese are results, not failures: the rewritten graph is the "
              "same function, so where it measures slower the base graph is "
              "kept for that lane and the rewrite contributes only the lanes "
              "it unlocked.")
    nc = [r for r in ledger if r["numerics_changing_us"]]
    if nc:
        print("\n### The numerics-CHANGING probe, measured and rejected\n")
        print("| network | lane | base | Elu->Relu probe | probe / best base lane |")
        print("|---|---|---|---|---|")
        for r in nc:
            bl = [x for x in ledger if x["network"] == r["network"] and x["adopted_us"]]
            best = min((x["adopted_us"] for x in bl), default=None)
            print(f"| `{r['network']}` | {r['lane']} | {ms(r['base_us'])} | "
                  f"{ms(r['numerics_changing_us'])} | "
                  f"{r['numerics_changing_us']/best:.1f}x |" if best else "|")
        print("\nSubstituting the activation is the only way `mlp_control` "
              "reaches HTA at all, and it is a different function. The probe "
              "exists so the decision is measured rather than argued; the "
              "measurement says HTA is an order of magnitude worse than the "
              "CPU for this network, so the answer is to accept CPU/DSP/GPU "
              "placement. Nothing from this row enters the cost model.")

    print("\n## 3. Granularity: the cut decision per network and rung\n")
    print("Break-even rule from `qnn_models/slicing_study/RESULTS.md` §7: an "
          "extra DSP dispatch costs `0.37 ms + 5.4 ns x boundary_bytes`, where "
          "`boundary_bytes` counts every tensor crossing the cut. Boundary "
          "bytes are read out of each rung's own ONNX.\n")
    print("| network | fastest lane | whole-net | candidate cut | cuts | "
          "boundary B | added dispatch | decision |")
    print("|---|---|---|---|---|---|---|---|")
    for r in gran:
        print(f"| `{r['network']}` | {r['fastest_lane']} | {r['fastest_ms']} ms | "
              f"{r['cut_candidates'][:40]} | {r['n_cuts']} | "
              f"{r['boundary_bytes']} | "
              f"{r['n_cuts'] * r['breakeven_dsp_ms']:.2f} ms | "
              f"**{r['decision']}** |")
    print("\nTwo distinct reasons, both measured:\n")
    print("* on `dronet_s*` and `mlp_control_s*` the added dispatch alone "
          "exceeds the whole network's critical path, so no assignment of the "
          "pieces can win;\n"
          "* on `yolov8_nano_s*` and `fastdepth` the dispatch is affordable, "
          "but Phase 1R's rewrites already made every lane reachable whole, so "
          "a cut buys no placement it does not already have — and placement is "
          "the only thing the slicing study found cutting ever buys.\n")
    print("`vint` is the exception and keeps its shipped two-tile split: there "
          "the cut genuinely does buy placement, because the monolith runs "
          "nowhere but the CPU while the encoder tile composes on the DSP.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
