#!/usr/bin/env python3
"""Phase 1a — build every network the ported sweep10 workloads need, as far as
a per-backend QNN context binary on the QRB5165, and record what composed.

The reference experiment (RoSE/experiments/sched_algo_sweep10) targets
`firesim_f2_rocket_saturn` and its networks are thin PyTorch wrapper modules in
modelblaster's own model zoo (models/<net>_s<k>.py, generated by
experiments/workload_gen/mk_scaled_variants.py). Flow C ingests PyTorch through
the same `extract_graph` on the same zoo, so those variants are ingestable here
without inventing new models -- which is the whole reason this replication is
possible.

Two facts govern this script:

  * The scale env var is read at IMPORT time of the backing module, so a
    process can only ever build ONE rung. Every export/extract therefore runs
    in its own subprocess.
  * The /scratch2 modelblaster submodule is pinned at 2026-08-27, which
    predates the `_s*` wrappers (2026-09-03) and fastdepth.py (2026-09-05). The
    zoo used here is therefore the RoSE working tree -- the SAME zoo the
    reference experiment used, which is the fidelity-maximising choice. Nothing
    is written into either tree; the IR and ONNX land under this sweep.

Precision per backend is not a free choice, it is what the backends accept
(measured in qnn_models/opsweep, see its README):

    hta   int8 only  -- a float DLC is rejected with `incorrect Datatype 0x508`
    dsp   int8 only  -- same
    cpu   fp32 here  -- int8-on-CPU is a reference kernel for conv and is
                        NUMERICALLY DEAD for mlp_control (constant output for
                        any input, measurements/qrb5165_v66.json). The int8
                        compose is still attempted and recorded, but the cell
                        this sweep solves against is fp32.
    gpu   fp16       -- the stock qti.aisw GPU package rejects every quantized
                        tensor at GPU_ERROR_INVALID_TYPE(10012) before any
                        op-specific check, so gpu/int8 does not exist.

A (tile, backend) pair that fails to compose is a RESULT, recorded with the
verbatim validator message, not an inconvenience to be worked around. No
offline ONNX rewrite is applied: the reference's networks are taken as the zoo
exports them, so the compose outcome describes those networks and not a
hand-tuned variant of them. (dronet's existing HTA context on this board only
exists because dronet.onnx was BN-rewritten, FC-head-replaced and
trailing-view-dropped offline by ad-hoc scripts that were never committed --
qnn_models/optimization_flow.md marks all three "(ad-hoc)". Reproducing that
per rung would make the scale ladder a ladder of three different graphs.)

    python3 phase1_build.py [--only dronet_sc,fastdepth] [--force] [--skip-board]
"""
from __future__ import annotations

import argparse, json, os, re, shutil, subprocess, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
SWEEP = os.path.abspath(os.path.join(HERE, ".."))
FLOWC = os.path.abspath(os.path.join(SWEEP, "..", ".."))
REPO = os.path.abspath(os.path.join(FLOWC, "..", ".."))

# The zoo that has the `_s*` rungs and fastdepth. See the docstring.
MB_ROOT = os.environ.get(
    "SWEEP10_MB_ROOT",
    "/scratch/dima/rose-infra/RoSE/soc/sw/xpu-rt/zephyr-chipyard-sw/modelblaster")
MB_PY = os.environ.get("SWEEP10_MB_PYTHON",
                       "/scratch2/dima/miniforge3/envs/xpurt/bin/python")
QNN_SDK = os.environ.get("QNN_SDK",
                         "/scratch2/dima/misc_sw/qualcomm/qairt/2.45.0.260326")
DOCKER_IMG = os.environ.get("QNN_DOCKER_IMG", "qnn-convert")
BOARD = os.environ.get("QNN_BOARD_HOST", "root@10.44.120.201")
BOARD_DLC = "/root/flowc_s10/dlc"
CTX_DIR = "/root/qnn_runtime_ctx"
SDK_BOARD = "/root/qairt"

GEN = os.path.join(SWEEP, "gen")
ONNX_DIR = os.path.join(GEN, "onnx")
IR_DIR = os.path.join(GEN, "ir")
DLC_DIR = os.path.join(GEN, "dlc")
CAL_DIR = os.path.join(GEN, "cal")
LOG_DIR = os.path.join(SWEEP, "logs", "phase1")
STATE = os.path.join(SWEEP, "results", "phase1_state.json")
OUT = os.path.join(SWEEP, "results", "phase1_compose.json")

#: (backend, precision, which DLC). Order matters only for the log.
BACKENDS = [
    ("hta", "int8", "q"),
    ("dsp", "int8", "q"),
    ("cpu", "fp32", "f"),
    ("cpu@int8", "int8", "q"),   # attempted and recorded; not the solved cell
    ("gpu", "fp16", "f"),
]
LIBOF = {"hta": "libQnnHta.so", "dsp": "libQnnDsp.so", "cpu": "libQnnCpu.so",
         "cpu@int8": "libQnnCpu.so", "gpu": "libQnnGpu.so"}
SUFFIX = {"hta": "Hta", "dsp": "Dsp", "cpu": "Cpu", "cpu@int8": "CpuInt8",
          "gpu": "Gpu"}

#: The reference experiment's network set. `identifier` is the modelblaster
#: model id; `family` groups the scale ladders. vint is NOT here -- it already
#: has a two-tile binding manifest and measured cells on this board, and is
#: reused as-is (see SETUP.md).
MODELS = [
    dict(id="dronet_sa", family="dronet"), dict(id="dronet_sb", family="dronet"),
    dict(id="dronet_sc", family="dronet"), dict(id="dronet_sd", family="dronet"),
    dict(id="dronet_se", family="dronet"), dict(id="dronet_sf", family="dronet"),
    dict(id="dronet_sg", family="dronet"),
    dict(id="mlp_control_sa", family="mlp_control"),
    dict(id="mlp_control_sb", family="mlp_control"),
    dict(id="mlp_control_sd", family="mlp_control"),
    dict(id="mlp_control_sf", family="mlp_control"),
    dict(id="yolov8_nano_sc", family="yolov8_nano"),
    dict(id="yolov8_nano_se", family="yolov8_nano"),
    dict(id="yolov8_nano_sf", family="yolov8_nano"),
    dict(id="yolov8_nano_sh", family="yolov8_nano"),
    dict(id="fastdepth", family="fastdepth"),
]

_EXPORT_SRC = r'''
import importlib, inspect, json, sys, torch
model_id, out_path, meta_path, opset = sys.argv[1:5]
mod = importlib.import_module("modelblaster.models." + model_id)
model = mod.get_model(); model.eval()
sample = mod.get_sample_input()
if isinstance(sample, (tuple, list)):
    names = [p for p in inspect.signature(model.forward).parameters
             if p != "self"][:len(sample)]
    args = tuple(sample); shapes = [list(t.shape) for t in sample]
else:
    names = ["input"]; args = (sample,); shapes = [list(sample.shape)]
torch.onnx.export(model, args, out_path, input_names=names,
                  output_names=["output"], opset_version=int(opset),
                  do_constant_folding=True, dynamo=False)
json.dump({"inputs": dict(zip(names, shapes))}, open(meta_path, "w"))
print("EXPORT_OK", json.dumps(dict(zip(names, shapes))))
'''


def log_path(name):
    os.makedirs(LOG_DIR, exist_ok=True)
    return os.path.join(LOG_DIR, name)


def run(cmd, log, timeout=1800, env=None, cwd=None):
    p = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout,
                       env=env, cwd=cwd)
    with open(log_path(log), "w") as f:
        f.write("+ " + " ".join(cmd) + f"\n(cwd={cwd})\n" + (p.stdout or "")
                + "\n--- stderr ---\n" + (p.stderr or ""))
    return p


def docker(script, log, timeout=3600):
    # --user: without it the daemon writes the converted DLCs as root:root
    # mode 640 into the mounted tree and the host cannot even read them back
    # (scp fails with EACCES, which `scp -q` would have swallowed).
    cmd = ["docker", "run", "--rm", "--user", f"{os.getuid()}:{os.getgid()}",
           "-v", f"{QNN_SDK}:/qnn:ro",
           "-v", f"{GEN}:/w", "-w", "/w", DOCKER_IMG, "bash", "-c", script]
    return run(cmd, log, timeout=timeout)


def board_sh(script, timeout=900):
    """One board interaction, serialised behind the shared board lock.

    `ssh -n` inside the flock -c chain: without it ssh swallows a heredoc on
    stdin and the result comes back silently empty.
    """
    q = script.replace("'", "'\\''")
    cmd = ["timeout", "-s", "KILL", str(timeout + 60), "ssh", "-n",
           "-o", "ConnectTimeout=20", "-o", "BatchMode=yes", BOARD,
           f"flock -w 900 /tmp/qnn_board.lock -c '{q}'"]
    return subprocess.run(cmd, capture_output=True, text=True,
                          timeout=timeout + 120)


def load_state():
    return json.load(open(STATE)) if os.path.exists(STATE) else {}


def save_state(st):
    os.makedirs(os.path.dirname(STATE), exist_ok=True)
    json.dump(st, open(STATE, "w"), indent=1)


def export_onnx(m, rec):
    """One subprocess per model: the rung's scale env var is read at import."""
    mid = m["id"]
    onnx = os.path.join(ONNX_DIR, f"{mid}.onnx")
    meta = os.path.join(ONNX_DIR, f"{mid}.inputs.json")
    os.makedirs(ONNX_DIR, exist_ok=True)
    env = dict(os.environ, PYTHONPATH=os.path.dirname(MB_ROOT))
    p = run([MB_PY, "-c", _EXPORT_SRC, mid, onnx, meta, "17"],
            f"export_{mid}.log", timeout=1800, env=env, cwd=MB_ROOT)
    rec["export_rc"] = p.returncode
    if p.returncode != 0 or not os.path.exists(onnx):
        rec["error"] = "onnx export failed"
        return False
    rec["onnx"] = os.path.relpath(onnx, SWEEP)
    rec["onnx_bytes"] = os.path.getsize(onnx)
    rec["inputs"] = json.load(open(meta))["inputs"]
    return True


def extract_ir(m, rec):
    """modelblaster's own extract_graph, out of process, in its own env."""
    mid = m["id"]
    out = os.path.join(IR_DIR, mid, "int8")
    os.makedirs(out, exist_ok=True)
    env = dict(os.environ,
               PYTHONPATH=os.path.join(MB_ROOT, "src") + os.pathsep
               + os.path.dirname(MB_ROOT))
    p = run([MB_PY, "-m", "modelblaster.pipeline.extract_graph", "--model", mid,
             "--out-dir", out, "--quant", "int8", "--num-calibration", "1"],
            f"ir_{mid}.log", timeout=3600, env=env, cwd=MB_ROOT)
    rec["ir_rc"] = p.returncode
    gj = os.path.join(out, "graph.json")
    if p.returncode != 0 or not os.path.exists(gj):
        rec["error"] = "extract_graph failed"
        return False
    d = json.load(open(gj))
    rec["graph_json"] = os.path.relpath(gj, SWEEP)
    rec["ir_ops"] = len(d.get("ops", []))
    from collections import Counter
    rec["ir_op_kinds"] = dict(Counter(o.get("op", "?") for o in d.get("ops", [])))
    # weights.npz / io.npz are large and are not needed downstream here.
    for junk in ("weights.npz", "io.npz"):
        fp = os.path.join(out, junk)
        if os.path.exists(fp):
            os.remove(fp)
    return True


_NWIN = re.compile(r"\b([\w/.:-]+)\s*\(data type:[^)]*\)\s*\[NW Input\]")
_DIMS = re.compile(r"\b([\w/.:-]+)\s+\(data type:[^)]*\)\s*\[NW Input\][^\n]*")


def onnx_to_dlc(m, rec):
    mid = m["id"]
    os.makedirs(DLC_DIR, exist_ok=True)
    rel_onnx = f"onnx/{mid}.onnx"
    rel_dlc = f"dlc/{mid}.dlc"
    # snpe-onnx-to-dlc emits a real .dlc that qnn-context-binary-generator
    # consumes; qnn-onnx-converter emits a .cpp+.bin model-lib pair that
    # context-binary-generator rejects with code 1002.
    p = docker(f"python3.10 /qnn/bin/x86_64-linux-clang/snpe-onnx-to-dlc "
               f"--input_network /w/{rel_onnx} --output_path /w/{rel_dlc} 2>&1 | tail -6",
               f"dlc_{mid}.log")
    rec["dlc_rc"] = p.returncode
    dlc = os.path.join(GEN, rel_dlc)
    if p.returncode != 0 or not os.path.exists(dlc):
        rec["error"] = "onnx->dlc failed"
        return False
    rec["dlc_bytes"] = os.path.getsize(dlc)
    mm = re.search(r"Total MACs:\s*(\d+)", p.stdout or "")
    rec["macs"] = int(mm.group(1)) if mm else None
    # Recover the DLC's OWN input names and shapes: snpe-onnx-to-dlc reorders
    # graph inputs by first-consumer position and may relayout, so the
    # calibration raws have to match the DLC and not the ONNX. snpe-dlc-info
    # prints a summary table at the end; parse that rather than the per-op
    # rows, which repeat static weights as "inputs".
    q = docker(f"/qnn/bin/x86_64-linux-clang/snpe-dlc-info -i /w/{rel_dlc} 2>&1",
               f"dlcinfo_{mid}.log")
    info = q.stdout or ""
    names, dims, inblock = [], [], False
    for line in info.splitlines():
        if re.match(r"\|\s*Input Name\s*\|", line):
            inblock = True
            continue
        if inblock:
            if line.startswith("---") or not line.strip():
                if names:
                    break
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) >= 2 and re.fullmatch(r"[0-9,]+", cells[1]):
                names.append(cells[0])
                dims.append([int(x) for x in cells[1].split(",")])
    rec["dlc_input_names"] = names or None
    rec["dlc_input_dims"] = dims or None
    gm = re.search(r"Graph Name:\s*(\S+)", info)
    rec["dlc_graph_name"] = gm.group(1) if gm else mid
    return True


def calibrate_and_quantize(m, rec, n_samples=10, seed=0):
    """Seeded float32 calibration raws, then qairt-quantizer.

    The raws are float32 for EVERY input whatever the DLC declares: a uint8 raw
    is a quarter of the expected extent and qairt-quantizer reports a bogus
    batch-size mismatch rather than a dtype error (qnn_models/opsweep/README).
    """
    import numpy as np
    mid = m["id"]
    cd = os.path.join(CAL_DIR, mid)
    shutil.rmtree(cd, ignore_errors=True)
    os.makedirs(cd, exist_ok=True)
    dims = rec.get("dlc_input_dims") or [list(v) for v in rec["inputs"].values()]
    rng = np.random.default_rng(seed)
    lines = []
    for i in range(n_samples):
        paths = []
        for j, d in enumerate(dims):
            a = rng.standard_normal(tuple(d)).astype(np.float32)
            fp = os.path.join(cd, f"in{j}_{i}.raw")
            a.tofile(fp)
            paths.append(f"/w/cal/{mid}/in{j}_{i}.raw")
        lines.append(" ".join(paths))
    with open(os.path.join(cd, "list.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    rec["calib"] = dict(n=n_samples, seed=seed, dims=dims)
    p = docker(f"/qnn/bin/x86_64-linux-clang/qairt-quantizer "
               f"--input_dlc /w/dlc/{mid}.dlc --output_dlc /w/dlc/{mid}_q.dlc "
               f"--input_list /w/cal/{mid}/list.txt 2>&1 | tail -8",
               f"quant_{mid}.log", timeout=7200)
    rec["quant_rc"] = p.returncode
    qdlc = os.path.join(DLC_DIR, f"{mid}_q.dlc")
    if p.returncode != 0 or not os.path.exists(qdlc):
        rec["quant_error"] = "quantize failed (see logs/phase1/quant_*.log)"
        return False
    rec["qdlc_bytes"] = os.path.getsize(qdlc)
    return True


COMPOSE = r'''
set +e
QNN={sdk}
export LD_LIBRARY_PATH=$QNN/lib/target
export ADSP_LIBRARY_PATH="$QNN/lib/hexagon-v66/unsigned;$QNN/lib/hexagon-v66;/dsp/cdsp;/dsp"
GEN=$QNN/bin/target/qnn-context-binary-generator
mkdir -p {ctx}
cd {bdlc}
for spec in {specs}; do
  be=$(echo "$spec" | cut -d: -f1); lib=$(echo "$spec" | cut -d: -f2)
  src=$(echo "$spec" | cut -d: -f3); out=$(echo "$spec" | cut -d: -f4)
  S=$(date +%s%N)
  "$GEN" --backend $QNN/lib/target/$lib \
         --model $QNN/lib/target/libQnnModelDlc.so \
         --dlc_path {bdlc}/$src --binary_file $out --output_dir {ctx} \
         > /tmp/_cmp_$out.log 2>&1
  rc=$?; E=$(date +%s%N)
  ms=$(( (E-S)/1000000 ))
  if [ $rc -eq 0 ]; then
    echo "RESULT $be OK $(stat -c%s {ctx}/$out.bin) $ms"
  else
    msg=$(grep -m3 -E "ERROR|unsupported|validation|Datatype|incorrect" /tmp/_cmp_$out.log | tr "\n" " | " | cut -c1-400)
    echo "RESULT $be FAIL rc=$rc 0 $ms :: $msg"
  fi
done
df -h / | tail -1
'''


def compose_on_board(m, rec):
    mid = m["id"]
    have_q = bool(rec.get("qdlc_bytes"))
    dlc = os.path.join(DLC_DIR, f"{mid}.dlc")
    qdlc = os.path.join(DLC_DIR, f"{mid}_q.dlc")
    push = [dlc] + ([qdlc] if have_q else [])
    r = subprocess.run(["timeout", "-s", "KILL", "900", "ssh", "-n",
                        "-o", "ConnectTimeout=20", "-o", "BatchMode=yes", BOARD,
                        f"mkdir -p {BOARD_DLC} {CTX_DIR}"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        rec["error"] = f"board mkdir failed: {r.stderr[-200:]}"
        return False
    r = subprocess.run(["timeout", "-s", "KILL", "1800", "scp", "-q",
                        "-o", "ConnectTimeout=20", "-o", "BatchMode=yes"]
                       + push + [f"{BOARD}:{BOARD_DLC}/"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        rec["error"] = f"scp dlc failed: {r.stderr[-300:]}"
        return False
    specs, plan = [], []
    for be, prec, which in BACKENDS:
        if which == "q" and not have_q:
            rec.setdefault("compose", {})[be] = dict(
                status="skipped", precision=prec,
                reason="no quantized DLC (quantize failed)")
            continue
        src = f"{mid}_q.dlc" if which == "q" else f"{mid}.dlc"
        out = f"ctx_s10_{mid}_{prec}__{SUFFIX[be]}"
        specs.append(f"{be}:{LIBOF[be]}:{src}:{out}")
        plan.append((be, prec, out))
    if not specs:
        return False
    script = COMPOSE.format(sdk=SDK_BOARD, ctx=CTX_DIR, bdlc=BOARD_DLC,
                            specs=" ".join(f'"{s}"' for s in specs))
    t0 = time.time()
    b = board_sh(script, timeout=2400)
    rec["compose_board_s"] = round(time.time() - t0, 1)
    out_by_be = {be: (prec, out) for be, prec, out in plan}
    seen = set()
    for line in (b.stdout or "").splitlines():
        if not line.startswith("RESULT "):
            if line.strip().startswith("/dev/root"):
                rec["board_df"] = line.strip()
            continue
        parts = line.split(None, 5)
        be, st = parts[1], parts[2]
        prec, out = out_by_be.get(be, ("?", "?"))
        seen.add(be)
        if st == "OK":
            rec.setdefault("compose", {})[be] = dict(
                status="ok", precision=prec, ctx=f"{out}.bin",
                bytes=int(parts[3]), compose_ms=int(parts[4]))
        else:
            tail = line.split("::", 1)[1].strip() if "::" in line else ""
            rec.setdefault("compose", {})[be] = dict(
                status="fail", precision=prec, ctx=f"{out}.bin",
                rc=parts[3], compose_ms=int(parts[5].split()[0]) if len(parts) > 5 else None,
                reason=tail or "(no message captured)")
    for be, prec, out in plan:
        if be not in seen:
            rec.setdefault("compose", {})[be] = dict(
                status="no_output", precision=prec,
                reason=(b.stderr or "")[-200:])
    rec["compose_stdout_tail"] = (b.stdout or "")[-400:]
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default=None)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--skip-board", action="store_true")
    a = ap.parse_args()
    want = set(a.only.split(",")) if a.only else None
    st = load_state()
    todo = [m for m in MODELS if not want or m["id"] in want]
    print(f"{len(todo)} model(s); zoo={MB_ROOT}")
    for m in todo:
        mid = m["id"]
        rec = st.setdefault(mid, {})
        rec["id"] = mid
        rec["family"] = m["family"]
        rec["zoo"] = MB_ROOT
        done = rec.get("stage") == "composed"
        if done and not a.force:
            ok = sum(1 for v in (rec.get("compose") or {}).values()
                     if v.get("status") == "ok")
            print(f"  {mid:<18} already built ({ok} backend(s) composed) — skipping")
            continue
        t0 = time.time()
        print(f"  {mid:<18} export…", end="", flush=True)
        if not export_onnx(m, rec):
            rec["stage"] = "export_failed"; save_state(st); print(" FAILED"); continue
        print(f" ir…", end="", flush=True)
        if not extract_ir(m, rec):
            rec["stage"] = "ir_failed"; save_state(st); print(" FAILED"); continue
        print(f" dlc…", end="", flush=True)
        if not onnx_to_dlc(m, rec):
            rec["stage"] = "dlc_failed"; save_state(st); print(" FAILED"); continue
        print(f" quant…", end="", flush=True)
        calibrate_and_quantize(m, rec)      # failure is recorded, not fatal
        rec["stage"] = "converted"
        save_state(st)
        if a.skip_board:
            print(f"  (board skipped)  {round(time.time()-t0,1)}s")
            continue
        print(f" compose…", end="", flush=True)
        compose_on_board(m, rec)
        rec["stage"] = "composed"
        rec["build_s"] = round(time.time() - t0, 1)
        save_state(st)
        cm = rec.get("compose") or {}
        good = [k for k, v in cm.items() if v.get("status") == "ok"]
        bad = [k for k, v in cm.items() if v.get("status") != "ok"]
        print(f" ok={sorted(good)} fail={sorted(bad)}  "
              f"{rec['ir_ops']} ir ops  {rec['build_s']}s")
    # flat record
    rows = [st[m["id"]] for m in MODELS if m["id"] in st]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    json.dump(rows, open(OUT, "w"), indent=1)
    nok = sum(1 for r in rows for v in (r.get("compose") or {}).values()
              if v.get("status") == "ok")
    ntot = sum(len(r.get("compose") or {}) for r in rows)
    print(f"\n{nok}/{ntot} (network, backend) pairs composed -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
